//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FingerprintACL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEnroll
    {
        public int ID { get; set; }
        public string StaffID { get; set; }
        public string Finger { get; set; }
        public byte[] Template { get; set; }
        public Nullable<short> quality { get; set; }
    }
}
